### ISSUE TITLE
Alignment and Font Size Adjustments

### ISSUE THREAD

**Issue by armoag** [wibsar/seiya-pos#8]
Pagina de Categorias
-Iconos no estan alineados
-La letra que este similar a los otros menus como por ejemplo el de agregar usuario (user details)

Corte
-Acomodar los botones cuando se pasa el mouse por ensima; no se ve como los demas

Menu Principal
-El color de Otros no es el mismo rojo que los demas aparentemente
- Checar si el de Gastos es el mismo verde, tambien me parece que no es

General
-Centrar vertical alignment en todas los textbox y tmb que la letra sea del mismo tamanho en todos
-Checar tamanho de letra en todas las listas como la del carrito, y la del inventario, etc
-Checar tamanho de letra en todo el programa

Corte
- El boton de pagar en efectivo debe alinear con el de pagar en rojo, creo que es mejor bajar el de pagar
- Checar cada pagina para que este alineado con lo del carrito de la derecha

**Comment by armoag** [comment]
@wichomr lo ves?

**Comment by wichomr** [comment]
Listo se suben las correcciones en el ultimo update
